import Header from "../../components/Header/Header";
import "./globals.css";

export const metadata = {
  title: "Ouassila - Planto Project",
  description: "Generated by create next app",
  icon: "/favicon.ico",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
 
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
